### PR TITLE
bugfix/metadata-source

### PR DESCRIPTION
**Pull request by baywet**
this PR addresses an issue where the metadata used by the unit test was different from the snippet generation one. This would create disparities on the changes introduced by the metadata cleanup process.

### CODE REVIEW

**Comment by baywet** [comment]
@zengin switching to this version of the metadata is more accurate but we have 20+ unit tests failing now, do you want to take on resolving the metadata issues/unit tests?

**Comment by zengin** [comment]
@baywet the failure is happening on the broken Beta metadata, which breaks all the tests as the initialization is happening at the beginning for all the tests. I removed the interdependency for V1 tests by delaying the initialization of the edm model.

**Review by zengin — APPROVED** [review]
@MichaelMainer is working on fixing the metadata issue. Once it is fixed, it should fix the unit tests here too.

**Comment by baywet** [comment]
Yeah I thought about moving to lazies from a perf perspective but I was lazy myself... Thanks for doing this!

**Review by andrueastman — APPROVED** [review]

**Comment by baywet** [comment]
For reference I'm guessing we're still waiting on https://github.com/microsoftgraph/msgraph-metadata/pull/48

**Comment by zengin** [comment]
@baywet, thanks for linking the metadata PR. Tests are passing locally if I update the github endpoint to @MIchaelMainer's metadata branch, but for merging I will wait on getting the green here for PR validation.

**Pull request merged**
